[default]
protoPath = ["src/", "/usr/local/src/googleapis/", "/usr/local/src/protobuf/src/"]
protoFile = ["echo/protobuf/echo.proto"]
package = "echo.v1"
service = "EchoService"

[server]
port = "8080" # don't work :(
host = "127.0.0.1"
